# Generated by Django 4.2.7 on 2023-11-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('home_team', models.IntegerField()),
                ('away_team', models.IntegerField()),
                ('winner', models.IntegerField()),
                ('date_played', models.DateField()),
                ('week_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('team_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('superbowl_champ', models.CharField(max_length=100)),
                ('MVP', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('year', models.IntegerField()),
                ('week_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('division', models.CharField(max_length=50)),
                ('team_name', models.CharField(max_length=100)),
            ],
        ),
    ]
